# Generated by Django 2.2.2 on 2019-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190627_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default='default.jpg', max_length=1000),
        ),
    ]
